AWSTemplateFormatVersion: '2010-09-09'
Description: Create WebACL with basic aws managed rules only 
Resources:
  BasicSecurityACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: BasicSecurityACL
      Scope: REGIONAL
      Description: This is a BasicSecurityACL
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: BasicSecurityACLMetric
      Rules:
        - Name: RuleWithAWSManagedRulesAmazonIpReputationList #VendorName: AWS, Name: AWSManagedRulesAmazonIpReputationList, WCU: 25
          Priority: 0
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: RuleWithAWSManagedRulesAmazonIpReputationList
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesAmazonIpReputationList
              ExcludedRules: []
        - Name: RuleWithAWSManagedRulesAnonymousIpList #VendorName: AWS, Name: AWSManagedRulesAnonymousIpList, WCU: 50
          Priority: 1
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: RuleWithAWSManagedRulesAnonymousIpList
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesAnonymousIpList
              ExcludedRules: []
        - Name: RuleWithAWSManagedRulesCommonRuleSet #VendorName: AWS, Name: AWSManagedRulesCommonRuleSet, WCU: 700
          Priority: 2
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: RuleWithAWSManagedRulesCommonRuleSet
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
              ExcludedRules: ['GenericLFI_BODY', 'GenericRFI_BODY']
        - Name: RuleWithAWSManagedRulesKnownBadInputsRuleSet #VendorName: AWS, Name: AWSManagedRulesKnownBadInputsRuleSet, WCU: 200
          Priority: 3
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: RuleWithAWSManagedRulesKnownBadInputsRuleSet
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesKnownBadInputsRuleSet
              ExcludedRules: []
        - Name: RuleWithAWSManagedRulesLinuxRuleSet #VendorName: AWS, Name: AWSManagedRulesLinuxRuleSet, WCU: 200
          Priority: 4
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: RuleWithAWSManagedRulesLinuxRuleSet
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesLinuxRuleSet
              ExcludedRules: []
        - Name: RuleWithAWSManagedRulesUnixRuleSet #VendorName: AWS, Name: AWSManagedRulesUnixRuleSet, WCU: 100
          Priority: 5
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: RuleWithAWSManagedRulesUnixRuleSet
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesUnixRuleSet
              ExcludedRules: []              
Outputs:
  BasicSecurityACLArn:
    Description: BasicSecurityACL arn
    Value: !GetAtt 'BasicSecurityACL.Arn'
    Export:
      Name: BasicSecurityACLArn