name: Verify and Release
on:
  push:
    branches:
      - main
permissions: write-all
env:
  javaVersion: java17

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        language: ['java']

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
      with:
        egress-policy: block
        allowed-endpoints: >
          api.adoptopenjdk.net:443
          api.github.com:443
          archive.apache.org:443
          azure.archive.ubuntu.com:80
          github.com:443
          maven.java.net:443
          maven.vaadin.com:443
          objects.githubusercontent.com:443
          oss.sonatype.org:443
          raw.githubusercontent.com:443
          repo.maven.apache.org:443
          repo.opennms.org:443
          repo1.maven.org:443
          repository.mulesoft.org:443
          tools.google.com:80
          tools.vaadin.com:443
          uploads.github.com:443
    - name: Checkout repository
      uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      with:
        # We must fetch at least the immediate parents so that if this is
        # a pull request then we can checkout the head.
        fetch-depth: 2

    - name: Set up JDK 17
      uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # v3.12.0
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Install buildtools
      run: sudo apt-get install -y graphviz build-essential fakeroot devscripts debhelper dh-make bzr-builddeb wget

    - name: Download Maven
      run: wget https://archive.apache.org/dist/maven/maven-3/3.9.4/binaries/apache-maven-3.9.4-bin.tar.gz

    - name: Unpack Maven
      run: tar xzvf apache-maven-3.9.4-bin.tar.gz

    - name: Set Maven
      run: mv apache-maven-3.9.4 maven
      
    - name: Build with Maven
      run: maven/bin/mvn -B install --file pom.xml -DskipTests
