name: Verify and Release
on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Version to release'
        required: true
permissions: write-all
env:
  javaVersion: java21

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      with:
        # We must fetch at least the immediate parents so that if this is
        # a pull request then we can checkout the head.
        fetch-depth: 2

    - name: Set up JDK 21
      uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3.13.0
      with:
        distribution: 'temurin'
        java-version: '21-ea'
        cache: 'maven'

    - name: Install buildtools
      run: sudo apt-get install -y graphviz build-essential fakeroot devscripts debhelper dh-make bzr-builddeb wget

    - name: Remove localtime
      run: sudo rm /etc/localtime

    - name: Set Swedish localtime
      run: sudo ln -s /usr/share/zoneinfo/Europe/Stockholm /etc/localtime 

    - name: Update tzdata
      run: sudo dpkg-reconfigure -f noninteractive tzdata 

    - name: Download Maven
      run: wget https://archive.apache.org/dist/maven/maven-3/3.9.4/binaries/apache-maven-3.9.4-bin.tar.gz

    - name: Unpack Maven
      run: tar xzvf apache-maven-3.9.4-bin.tar.gz

    - name: Set Maven
      run: mv apache-maven-3.9.4 maven
      
    - name: Build with Maven
      run: maven/bin/mvn -B --file pom.xml clean install -Prelease-site,all-modules -DforkMode=once '-Dtest=!**ITest*,!**DocumentationTest*' -DfailIfNoTests=false  -Dsurefire.failIfNoSpecifiedTests=false  -Dsurefire.reportNameSuffix=UNIT

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@fcfbdceb3093f6d85a3b194740f8c6cec632f4e2 # v6.1
      with:
        github_token: ${{ github.token }}
    - name: Create a GitHub release
      uses: ncipollo/release-action@6c75be85e571768fa31b40abf38de58ba0397db5 # v1.13.0
      with:
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}
